name: SonarQube Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SonarQube
        uses: sonarsource/sonarqube-scan@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sqa_fe8e5bd1e47df6118965358e6b1d6f54a2831c6b
            -Dsonar.sources=.
            # Add any additional analysis parameters here

      # Add any additional steps you need for your workflow
